export interface CatalogPlan {
  name: string;
  monthly: number;
  deployedApps: number;
  developerApps: number;
  concurrentInstances: number;
  ramMb: number;
  includedGbHours: number;
  appLayerMb: number;
  idleTimeout: string;
}

/** The upstream Markdown is generated by make pricing-md from API limits.go.
 * Reject format changes during build rather than publishing guessed prices. */
export function parsePlanCatalog(source: string): {
  currency: 'EUR';
  overagePerGbHour: number;
  plans: CatalogPlan[];
} {
  const header =
    '| Plan | Monthly | Deployed apps | Developer apps | Concurrent instances | RAM / app | Included GB-RAM-hours | App layer | Idle timeout |';
  if (!source.includes('<!-- GENERATED') || !source.includes(header)) {
    throw new Error('Unrecognised generated plan catalog');
  }
  const rate = /billed at €(\d+(?:\.\d+)?) per GB-RAM-hour/.exec(source);
  if (!rate) throw new Error('Missing EUR overage rate');
  const rows = source.split('\n').filter((line) => line.startsWith('| **'));
  const plans = rows.map((line): CatalogPlan => {
    const cells = line
      .split('|')
      .slice(1, -1)
      .map((cell) => cell.trim());
    const patterns = [
      /^\*\*([A-Za-z]+)\*\*$/,
      /^€(\d+(?:\.\d+)?)$/,
      /^(\d+)$/,
      /^(\d+)$/,
      /^(\d+)$/,
      /^(\d+) MB$/,
      /^(\d+)$/,
      /^(\d+) MB$/,
      /^(\d+[smh])$/,
    ];
    const values = patterns.map((pattern, index) => pattern.exec(cells[index] ?? '')?.[1]);
    if (cells.length !== patterns.length || values.some((value) => value === undefined)) {
      throw new Error(`Invalid plan row: ${line}`);
    }
    return {
      name: values[0]!,
      monthly: Number(values[1]),
      deployedApps: Number(values[2]),
      developerApps: Number(values[3]),
      concurrentInstances: Number(values[4]),
      ramMb: Number(values[5]),
      includedGbHours: Number(values[6]),
      appLayerMb: Number(values[7]),
      idleTimeout: values[8]!,
    };
  });
  if (plans.map((plan) => plan.name).join(',') !== 'Free,Hobby,Pro,Scale') {
    throw new Error('Unexpected self-service plan set');
  }
  return { currency: 'EUR', overagePerGbHour: Number(rate[1]), plans };
}
