import type { RuntimePolicy } from '@/lib/api/runtime-policy';
export const gateway = {
  scope: 'app' as const,
  desired_revision: 5,
  state: 'active' as const,
  serving_gateways: 2,
  applied_gateways: 2,
  pending_gateways: 0,
  stale_gateways: 0,
};
export const status: RuntimePolicy = {
  app_id: 'app-1',
  desired_revision: 10,
  state: 'active',
  coverage: [],
  serving_gateways: 2,
  applied_gateways: 2,
  pending_gateways: 0,
  stale_gateways: 0,
  request_policy: gateway,
  edge_rules: { ...gateway, state: 'pending', applied_gateways: 1, pending_gateways: 1 },
  cors_presets: { ...gateway, scope: 'account' },
  response_cache: { ...gateway, state: 'pending', applied_gateways: 1, pending_gateways: 1 },
  egress_allowlist: {
    scope: 'app',
    desired_revision: 5,
    state: 'active',
    serving_nodes: 1,
    applied_nodes: 1,
    pending_nodes: 0,
    stale_nodes: 0,
  },
  cpu_limit: {
    scope: 'app',
    desired_revision: 5,
    state: 'pending',
    serving_nodes: 1,
    applied_nodes: 0,
    pending_nodes: 1,
    stale_nodes: 0,
  },
  scheduler_scaling: {
    scope: 'app',
    desired_revision: 5,
    observed_revision: 5,
    state: 'active',
    stale: false,
    observed_at: '2026-10-09T10:00:00Z',
  },
};
