/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardApisRouteImport } from './routes/dashboard.apis'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardBuildsRouteImport } from './routes/dashboard.builds'
import { Route as DashboardCronsRouteImport } from './routes/dashboard.crons'
import { Route as DashboardDatabasesRouteImport } from './routes/dashboard.databases'
import { Route as DashboardDebugRouteImport } from './routes/dashboard.debug'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard.deployments'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardEdgeRulesRouteImport } from './routes/dashboard.edge-rules'
import { Route as DashboardEnvRouteImport } from './routes/dashboard.env'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardMetricsRouteImport } from './routes/dashboard.metrics'
import { Route as DashboardMirrorsRouteImport } from './routes/dashboard.mirrors'
import { Route as DashboardOpenapiRouteImport } from './routes/dashboard.openapi'
import { Route as DashboardPlansRouteImport } from './routes/dashboard.plans'
import { Route as DashboardPostgresRouteImport } from './routes/dashboard.postgres'
import { Route as DashboardQueuesRouteImport } from './routes/dashboard.queues'
import { Route as DashboardSecretsRouteImport } from './routes/dashboard.secrets'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTenantSurfacesRouteImport } from './routes/dashboard.tenant-surfaces'
import { Route as DashboardTracesRouteImport } from './routes/dashboard.traces'
import { Route as DashboardTriggersRouteImport } from './routes/dashboard.triggers'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardWorkersRouteImport } from './routes/dashboard.workers'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as StatusIndexRouteImport } from './routes/status.index'
import { Route as DashboardTriggersTriggerIdRouteImport } from './routes/dashboard.triggers.$triggerId'
import { Route as DashboardTriggersNewRouteImport } from './routes/dashboard.triggers.new'
import { Route as DashboardWorkflowsIndexRouteImport } from './routes/dashboard.workflows.index'
import { Route as DashboardWorkflowsWorkflowIdRouteImport } from './routes/dashboard.workflows.$workflowId'
import { Route as DashboardWorkflowsNewRouteImport } from './routes/dashboard.workflows.new'
import { Route as StatusIncidentsIdRouteImport } from './routes/status.incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApisRoute = DashboardApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuildsRoute = DashboardBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCronsRoute = DashboardCronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebugRoute = DashboardDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEdgeRulesRoute = DashboardEdgeRulesRouteImport.update({
  id: '/edge-rules',
  path: '/edge-rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnvRoute = DashboardEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricsRoute = DashboardMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMirrorsRoute = DashboardMirrorsRouteImport.update({
  id: '/mirrors',
  path: '/mirrors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpenapiRoute = DashboardOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansRoute = DashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostgresRoute = DashboardPostgresRouteImport.update({
  id: '/postgres',
  path: '/postgres',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueuesRoute = DashboardQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecretsRoute = DashboardSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTenantSurfacesRoute = DashboardTenantSurfacesRouteImport.update({
  id: '/tenant-surfaces',
  path: '/tenant-surfaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracesRoute = DashboardTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTriggersRoute = DashboardTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatusRoute,
} as any)
const DashboardTriggersTriggerIdRoute =
  DashboardTriggersTriggerIdRouteImport.update({
    id: '/$triggerId',
    path: '/$triggerId',
    getParentRoute: () => DashboardTriggersRoute,
  } as any)
const DashboardTriggersNewRoute = DashboardTriggersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardTriggersRoute,
} as any)
const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkflowsWorkflowIdRoute =
  DashboardWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkflowsNewRoute = DashboardWorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => DashboardRoute,
} as any)
const StatusIncidentsIdRoute = StatusIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => StatusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/mirrors': typeof DashboardMirrorsRoute
  '/dashboard/openapi': typeof DashboardOpenapiRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/postgres': typeof DashboardPostgresRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tenant-surfaces': typeof DashboardTenantSurfacesRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/triggers': typeof DashboardTriggersRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/dashboard/triggers/$triggerId': typeof DashboardTriggersTriggerIdRoute
  '/dashboard/triggers/new': typeof DashboardTriggersNewRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/status/incidents/$id': typeof StatusIncidentsIdRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/mirrors': typeof DashboardMirrorsRoute
  '/dashboard/openapi': typeof DashboardOpenapiRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/postgres': typeof DashboardPostgresRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tenant-surfaces': typeof DashboardTenantSurfacesRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/triggers': typeof DashboardTriggersRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/status': typeof StatusIndexRoute
  '/dashboard/triggers/$triggerId': typeof DashboardTriggersTriggerIdRoute
  '/dashboard/triggers/new': typeof DashboardTriggersNewRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/status/incidents/$id': typeof StatusIncidentsIdRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/debug': typeof DashboardDebugRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/mirrors': typeof DashboardMirrorsRoute
  '/dashboard/openapi': typeof DashboardOpenapiRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/postgres': typeof DashboardPostgresRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tenant-surfaces': typeof DashboardTenantSurfacesRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/triggers': typeof DashboardTriggersRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/dashboard/triggers/$triggerId': typeof DashboardTriggersTriggerIdRoute
  '/dashboard/triggers/new': typeof DashboardTriggersNewRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/status/incidents/$id': typeof StatusIncidentsIdRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/status'
    | '/dashboard/account'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/debug'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/import'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/mirrors'
    | '/dashboard/openapi'
    | '/dashboard/plans'
    | '/dashboard/postgres'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tenant-surfaces'
    | '/dashboard/traces'
    | '/dashboard/triggers'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/docs/'
    | '/status/'
    | '/dashboard/triggers/$triggerId'
    | '/dashboard/triggers/new'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/status/incidents/$id'
    | '/dashboard/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/debug'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/import'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/mirrors'
    | '/dashboard/openapi'
    | '/dashboard/plans'
    | '/dashboard/postgres'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tenant-surfaces'
    | '/dashboard/traces'
    | '/dashboard/triggers'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/invite/$token'
    | '/dashboard'
    | '/docs'
    | '/status'
    | '/dashboard/triggers/$triggerId'
    | '/dashboard/triggers/new'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/status/incidents/$id'
    | '/dashboard/workflows'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/status'
    | '/dashboard/account'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/debug'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/import'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/mirrors'
    | '/dashboard/openapi'
    | '/dashboard/plans'
    | '/dashboard/postgres'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tenant-surfaces'
    | '/dashboard/traces'
    | '/dashboard/triggers'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/docs/'
    | '/status/'
    | '/dashboard/triggers/$triggerId'
    | '/dashboard/triggers/new'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/status/incidents/$id'
    | '/dashboard/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apis': {
      id: '/dashboard/apis'
      path: '/apis'
      fullPath: '/dashboard/apis'
      preLoaderRoute: typeof DashboardApisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builds': {
      id: '/dashboard/builds'
      path: '/builds'
      fullPath: '/dashboard/builds'
      preLoaderRoute: typeof DashboardBuildsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crons': {
      id: '/dashboard/crons'
      path: '/crons'
      fullPath: '/dashboard/crons'
      preLoaderRoute: typeof DashboardCronsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/databases': {
      id: '/dashboard/databases'
      path: '/databases'
      fullPath: '/dashboard/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/debug': {
      id: '/dashboard/debug'
      path: '/debug'
      fullPath: '/dashboard/debug'
      preLoaderRoute: typeof DashboardDebugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edge-rules': {
      id: '/dashboard/edge-rules'
      path: '/edge-rules'
      fullPath: '/dashboard/edge-rules'
      preLoaderRoute: typeof DashboardEdgeRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/env': {
      id: '/dashboard/env'
      path: '/env'
      fullPath: '/dashboard/env'
      preLoaderRoute: typeof DashboardEnvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metrics': {
      id: '/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof DashboardMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mirrors': {
      id: '/dashboard/mirrors'
      path: '/mirrors'
      fullPath: '/dashboard/mirrors'
      preLoaderRoute: typeof DashboardMirrorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/openapi': {
      id: '/dashboard/openapi'
      path: '/openapi'
      fullPath: '/dashboard/openapi'
      preLoaderRoute: typeof DashboardOpenapiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans': {
      id: '/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof DashboardPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/postgres': {
      id: '/dashboard/postgres'
      path: '/postgres'
      fullPath: '/dashboard/postgres'
      preLoaderRoute: typeof DashboardPostgresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queues': {
      id: '/dashboard/queues'
      path: '/queues'
      fullPath: '/dashboard/queues'
      preLoaderRoute: typeof DashboardQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/secrets': {
      id: '/dashboard/secrets'
      path: '/secrets'
      fullPath: '/dashboard/secrets'
      preLoaderRoute: typeof DashboardSecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tenant-surfaces': {
      id: '/dashboard/tenant-surfaces'
      path: '/tenant-surfaces'
      fullPath: '/dashboard/tenant-surfaces'
      preLoaderRoute: typeof DashboardTenantSurfacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/traces': {
      id: '/dashboard/traces'
      path: '/traces'
      fullPath: '/dashboard/traces'
      preLoaderRoute: typeof DashboardTracesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/triggers': {
      id: '/dashboard/triggers'
      path: '/triggers'
      fullPath: '/dashboard/triggers'
      preLoaderRoute: typeof DashboardTriggersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers': {
      id: '/dashboard/workers'
      path: '/workers'
      fullPath: '/dashboard/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof StatusRoute
    }
    '/dashboard/triggers/$triggerId': {
      id: '/dashboard/triggers/$triggerId'
      path: '/$triggerId'
      fullPath: '/dashboard/triggers/$triggerId'
      preLoaderRoute: typeof DashboardTriggersTriggerIdRouteImport
      parentRoute: typeof DashboardTriggersRoute
    }
    '/dashboard/triggers/new': {
      id: '/dashboard/triggers/new'
      path: '/new'
      fullPath: '/dashboard/triggers/new'
      preLoaderRoute: typeof DashboardTriggersNewRouteImport
      parentRoute: typeof DashboardTriggersRoute
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows/'
      preLoaderRoute: typeof DashboardWorkflowsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/$workflowId': {
      id: '/dashboard/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/dashboard/workflows/$workflowId'
      preLoaderRoute: typeof DashboardWorkflowsWorkflowIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/new': {
      id: '/dashboard/workflows/new'
      path: '/workflows/new'
      fullPath: '/dashboard/workflows/new'
      preLoaderRoute: typeof DashboardWorkflowsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/status/incidents/$id': {
      id: '/status/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/status/incidents/$id'
      preLoaderRoute: typeof StatusIncidentsIdRouteImport
      parentRoute: typeof StatusRoute
    }
  }
}

interface DashboardTriggersRouteChildren {
  DashboardTriggersTriggerIdRoute: typeof DashboardTriggersTriggerIdRoute
  DashboardTriggersNewRoute: typeof DashboardTriggersNewRoute
}

const DashboardTriggersRouteChildren: DashboardTriggersRouteChildren = {
  DashboardTriggersTriggerIdRoute: DashboardTriggersTriggerIdRoute,
  DashboardTriggersNewRoute: DashboardTriggersNewRoute,
}

const DashboardTriggersRouteWithChildren =
  DashboardTriggersRoute._addFileChildren(DashboardTriggersRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApisRoute: typeof DashboardApisRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBuildsRoute: typeof DashboardBuildsRoute
  DashboardCronsRoute: typeof DashboardCronsRoute
  DashboardDatabasesRoute: typeof DashboardDatabasesRoute
  DashboardDebugRoute: typeof DashboardDebugRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardEdgeRulesRoute: typeof DashboardEdgeRulesRoute
  DashboardEnvRoute: typeof DashboardEnvRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMetricsRoute: typeof DashboardMetricsRoute
  DashboardMirrorsRoute: typeof DashboardMirrorsRoute
  DashboardOpenapiRoute: typeof DashboardOpenapiRoute
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardPostgresRoute: typeof DashboardPostgresRoute
  DashboardQueuesRoute: typeof DashboardQueuesRoute
  DashboardSecretsRoute: typeof DashboardSecretsRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardTenantSurfacesRoute: typeof DashboardTenantSurfacesRoute
  DashboardTracesRoute: typeof DashboardTracesRoute
  DashboardTriggersRoute: typeof DashboardTriggersRouteWithChildren
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardWorkersRoute: typeof DashboardWorkersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkflowsWorkflowIdRoute: typeof DashboardWorkflowsWorkflowIdRoute
  DashboardWorkflowsNewRoute: typeof DashboardWorkflowsNewRoute
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApisRoute: DashboardApisRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBuildsRoute: DashboardBuildsRoute,
  DashboardCronsRoute: DashboardCronsRoute,
  DashboardDatabasesRoute: DashboardDatabasesRoute,
  DashboardDebugRoute: DashboardDebugRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardEdgeRulesRoute: DashboardEdgeRulesRoute,
  DashboardEnvRoute: DashboardEnvRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMetricsRoute: DashboardMetricsRoute,
  DashboardMirrorsRoute: DashboardMirrorsRoute,
  DashboardOpenapiRoute: DashboardOpenapiRoute,
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardPostgresRoute: DashboardPostgresRoute,
  DashboardQueuesRoute: DashboardQueuesRoute,
  DashboardSecretsRoute: DashboardSecretsRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardTenantSurfacesRoute: DashboardTenantSurfacesRoute,
  DashboardTracesRoute: DashboardTracesRoute,
  DashboardTriggersRoute: DashboardTriggersRouteWithChildren,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardWorkersRoute: DashboardWorkersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkflowsWorkflowIdRoute: DashboardWorkflowsWorkflowIdRoute,
  DashboardWorkflowsNewRoute: DashboardWorkflowsNewRoute,
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface StatusRouteChildren {
  StatusIndexRoute: typeof StatusIndexRoute
  StatusIncidentsIdRoute: typeof StatusIncidentsIdRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusIndexRoute: StatusIndexRoute,
  StatusIncidentsIdRoute: StatusIncidentsIdRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
