/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardApisRouteImport } from './routes/dashboard.apis'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardBuildsRouteImport } from './routes/dashboard.builds'
import { Route as DashboardCronsRouteImport } from './routes/dashboard.crons'
import { Route as DashboardDatabasesRouteImport } from './routes/dashboard.databases'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard.deployments'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardEdgeRulesRouteImport } from './routes/dashboard.edge-rules'
import { Route as DashboardEnvRouteImport } from './routes/dashboard.env'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardMetricsRouteImport } from './routes/dashboard.metrics'
import { Route as DashboardPlansRouteImport } from './routes/dashboard.plans'
import { Route as DashboardQueuesRouteImport } from './routes/dashboard.queues'
import { Route as DashboardSecretsRouteImport } from './routes/dashboard.secrets'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardTracesRouteImport } from './routes/dashboard.traces'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardWorkersRouteImport } from './routes/dashboard.workers'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DashboardWorkflowsIndexRouteImport } from './routes/dashboard.workflows.index'
import { Route as DashboardWorkflowsWorkflowIdRouteImport } from './routes/dashboard.workflows.$workflowId'
import { Route as DashboardWorkflowsNewRouteImport } from './routes/dashboard.workflows.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApisRoute = DashboardApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuildsRoute = DashboardBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCronsRoute = DashboardCronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEdgeRulesRoute = DashboardEdgeRulesRouteImport.update({
  id: '/edge-rules',
  path: '/edge-rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnvRoute = DashboardEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricsRoute = DashboardMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansRoute = DashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueuesRoute = DashboardQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecretsRoute = DashboardSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracesRoute = DashboardTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkflowsWorkflowIdRoute =
  DashboardWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkflowsNewRoute = DashboardWorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/builds': typeof DashboardBuildsRoute
  '/dashboard/crons': typeof DashboardCronsRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/edge-rules': typeof DashboardEdgeRulesRoute
  '/dashboard/env': typeof DashboardEnvRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/queues': typeof DashboardQueuesRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/workflows/$workflowId': typeof DashboardWorkflowsWorkflowIdRoute
  '/dashboard/workflows/new': typeof DashboardWorkflowsNewRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/invoices'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/plans'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/traces'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/dashboard/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/invoices'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/plans'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/traces'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/dashboard'
    | '/docs'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/dashboard/workflows'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/alerts'
    | '/dashboard/apis'
    | '/dashboard/audit'
    | '/dashboard/builds'
    | '/dashboard/crons'
    | '/dashboard/databases'
    | '/dashboard/deployments'
    | '/dashboard/domains'
    | '/dashboard/edge-rules'
    | '/dashboard/env'
    | '/dashboard/invoices'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/metrics'
    | '/dashboard/plans'
    | '/dashboard/queues'
    | '/dashboard/secrets'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/team'
    | '/dashboard/traces'
    | '/dashboard/usage'
    | '/dashboard/webhooks'
    | '/dashboard/workers'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/workflows/$workflowId'
    | '/dashboard/workflows/new'
    | '/dashboard/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apis': {
      id: '/dashboard/apis'
      path: '/apis'
      fullPath: '/dashboard/apis'
      preLoaderRoute: typeof DashboardApisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builds': {
      id: '/dashboard/builds'
      path: '/builds'
      fullPath: '/dashboard/builds'
      preLoaderRoute: typeof DashboardBuildsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crons': {
      id: '/dashboard/crons'
      path: '/crons'
      fullPath: '/dashboard/crons'
      preLoaderRoute: typeof DashboardCronsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/databases': {
      id: '/dashboard/databases'
      path: '/databases'
      fullPath: '/dashboard/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edge-rules': {
      id: '/dashboard/edge-rules'
      path: '/edge-rules'
      fullPath: '/dashboard/edge-rules'
      preLoaderRoute: typeof DashboardEdgeRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/env': {
      id: '/dashboard/env'
      path: '/env'
      fullPath: '/dashboard/env'
      preLoaderRoute: typeof DashboardEnvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metrics': {
      id: '/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof DashboardMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans': {
      id: '/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof DashboardPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queues': {
      id: '/dashboard/queues'
      path: '/queues'
      fullPath: '/dashboard/queues'
      preLoaderRoute: typeof DashboardQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/secrets': {
      id: '/dashboard/secrets'
      path: '/secrets'
      fullPath: '/dashboard/secrets'
      preLoaderRoute: typeof DashboardSecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/traces': {
      id: '/dashboard/traces'
      path: '/traces'
      fullPath: '/dashboard/traces'
      preLoaderRoute: typeof DashboardTracesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers': {
      id: '/dashboard/workers'
      path: '/workers'
      fullPath: '/dashboard/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows/'
      preLoaderRoute: typeof DashboardWorkflowsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/$workflowId': {
      id: '/dashboard/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/dashboard/workflows/$workflowId'
      preLoaderRoute: typeof DashboardWorkflowsWorkflowIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/new': {
      id: '/dashboard/workflows/new'
      path: '/workflows/new'
      fullPath: '/dashboard/workflows/new'
      preLoaderRoute: typeof DashboardWorkflowsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardApisRoute: typeof DashboardApisRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBuildsRoute: typeof DashboardBuildsRoute
  DashboardCronsRoute: typeof DashboardCronsRoute
  DashboardDatabasesRoute: typeof DashboardDatabasesRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardEdgeRulesRoute: typeof DashboardEdgeRulesRoute
  DashboardEnvRoute: typeof DashboardEnvRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMetricsRoute: typeof DashboardMetricsRoute
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardQueuesRoute: typeof DashboardQueuesRoute
  DashboardSecretsRoute: typeof DashboardSecretsRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTracesRoute: typeof DashboardTracesRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardWorkersRoute: typeof DashboardWorkersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkflowsWorkflowIdRoute: typeof DashboardWorkflowsWorkflowIdRoute
  DashboardWorkflowsNewRoute: typeof DashboardWorkflowsNewRoute
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardApisRoute: DashboardApisRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBuildsRoute: DashboardBuildsRoute,
  DashboardCronsRoute: DashboardCronsRoute,
  DashboardDatabasesRoute: DashboardDatabasesRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardEdgeRulesRoute: DashboardEdgeRulesRoute,
  DashboardEnvRoute: DashboardEnvRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMetricsRoute: DashboardMetricsRoute,
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardQueuesRoute: DashboardQueuesRoute,
  DashboardSecretsRoute: DashboardSecretsRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTracesRoute: DashboardTracesRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardWorkersRoute: DashboardWorkersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkflowsWorkflowIdRoute: DashboardWorkflowsWorkflowIdRoute,
  DashboardWorkflowsNewRoute: DashboardWorkflowsNewRoute,
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
